
# Created by: SomitraSR
# Web application CloudFormation script for aws.

Description:
  < SomitraSR
  CloudFormation

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names.
    Type: String
    
  ProjectName:
    Description: The project name you're working on.
    Type: String

  EC2AccessKeyPair:
    Description: The Key Pair name used to access the EC2 via SSH.
    Type: String

  EC2InstanceProfileRole:
    Description: IAM Role profile to be used when launching an EC2 Instance.
    Type: String

  
   
Resources:
# EC2 Launch Configuration
  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          aws s3 cp s3://somitrasr/build.zip .
          unzip -o build.zip
      ImageId: ami-071c0caeb8fcd3fbc # Ubuntu Server 18.04 LTS (HVM), SSD Volume Type
      IamInstanceProfile: !Ref EC2InstanceProfileRole
      SecurityGroups:
      - Fn::ImportValue: 
          !Sub "${ProjectName}-WebSecurityGroupID"
      InstanceType: t3.small
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          VolumeSize: '12'
  
  # AutoScaling Group        
  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      # List Private Subnet IDs
      VPCZoneIdentifier: 
        - Fn::ImportValue: !Sub ${ProjectName}-Private-Subnet-IDs
      LaunchConfigurationName: !Ref WebAppLaunchConfig
      MinSize: '2'
      MaxSize: '6'
      TargetGroupARNs:
      - Ref: WebAppTargetGroup
      Tags:
        - Key: Name
          Value: EC2 Instance
          PropagateAtLaunch: true
        - Key: ProjectName
          Value: !Sub ${ProjectName}
          PropagateAtLaunch: true

  # Load Balancer
  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
      - Fn::ImportValue: !Sub ${ProjectName}-Public-Subnet-1-ID
      - Fn::ImportValue: !Sub ${ProjectName}-Public-Subnet-2-ID
      SecurityGroups:
      - Fn::ImportValue: !Sub ${ProjectName}-LBSecurityGroupID
      Tags:
        - Key: Name
          Value: Load Balancer
        - Key: ProjectName
          Value: !Sub ${ProjectName}
    
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref WebAppTargetGroup
      LoadBalancerArn: !Ref WebAppLB
      Port: '80'
      Protocol: HTTP
  
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref WebAppTargetGroup
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn: !Ref Listener
      Priority: 1

  WebAppTargetGroup:
  ## Checks for an HTTP response
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: / # Filepath of what you want to check.
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${ProjectName}-VPCID"

Outputs:

  LoadBalancerDNS:
    Description: The URL of the Udagram Site
    Value: 
      !Sub
        - 'http://${LoadBalancerDNS}'
        - {LoadBalancerDNS: !GetAtt 'WebAppLB.DNSName'}
    Export:
      Name: !Sub "${ProjectName}-SiteURL"


